# -*- coding: utf-8 -*-
"""Notebook_Scraping_Analisis_Sentimen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSJqyrsm0lmKxChp5wYYhJal0r1euscb
"""

!pip install google-play-scraper

"""*Import Libary*"""

from google_play_scraper import reviews, reviews_all, Sort
import pandas as pd

"""*Melakukan scraping ulasan aplikasi shopee*"""

scrapreview = reviews (
    'com.shopee.id',       # Shopee ID
    lang='id',             # Bahasa Indonesia
    country='id',          # Negara Indonesia
    sort=Sort.NEWEST,      # Review terbaru
    count=12000           # Jumlah ulasan yang ingin diambil
)

"""*Menyimpan hasilnya menjadi file csv*"""

# scrapreview adalah tuple (data, continuation_token)
df = pd.DataFrame(scrapreview[0])   # ambil index 0 untuk datanya
df = df[['userName', 'content', 'score', 'at']]
df.to_csv('ulasan_aplikasi_shopee.csv', index=False)
print(f"Total data tersimpan: {len(df)}")

df.head()