# -*- coding: utf-8 -*-
"""Pelatihan_Model_Analisis_Sentimen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AaDefYiWRP19-X5kJvy7mfKr3ZUFETcm

**Menginstal libary yang dibutuhkan**
"""

!pip install google-play-scraper
!pip install Sastrawi
!pip install nltk
!pip install gensim
!pip install scikit-learn
!pip install pandas numpy matplotlib

"""**Import semua libary yang dibutuhkan**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import nltk
import string
import seaborn as sns
import datetime as dt
from nltk.tokenize import word_tokenize

# libary NLP bahasa Indonesia
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# libary Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
from sklearn.utils import resample
from gensim.models import Word2Vec

"""**Load Dataset**"""

df = pd.read_csv('ulasan_aplikasi_shopee.csv')

print(f"total data: {len(df)}")
print(f"kolom: {df.columns.tolist()}")
print(f"tabel data:")
df.head() # menampilkan 5 data teratas

df.info() # menampilkan info dataset

"""**Data preparation**"""

clean_df = df.dropna(subset=['content']) # menghapus data yang kosong
clean_df = clean_df.drop_duplicates() # menghapus data yang duplikat
clean_df = clean_df.reset_index(drop=True) # mereset index setelah data dihapus

print(f"Total data setelah cleaning: {len(clean_df)}")
clean_df.info()

"""**Inisialisasi Sastrawi**"""

# stemmer mengubah kata berimbuhan menjadi kata dasar
# stopword menghapus kata yang tidak terlalu penting
# download resource nltk yang dibutuhkan

import nltk
nltk.download('stopwords')   # untuk filteringText
nltk.download('punkt')       # untuk tokenizingText (word_tokenize)
nltk.download('punkt_tab')   # untuk tokenizingText versi yang terbaru

factory_stemmer = StemmerFactory()
stemmer = factory_stemmer.create_stemmer()
factory_stopword = StopWordRemoverFactory()
stopword = factory_stopword.create_stop_word_remover()

"""**Preprocessing text**"""

def cleaningText(text):
    text = re.sub(r'RT[\s]', '', text)                                 # menghapus RT
    text = re.sub(r"http\S+", '', text)                                # menghapus link
    text = re.sub(r'[0-9]+', '', text)                                 # menghapus angka
    text = re.sub(r'#[A-Za-z0-9]+', '', text)                          # menghapus hashtag
    text = re.sub(r'@[A-Za-z0-9]+', '', text)                          # menghapus mention
    text = re.sub(r'[^\w\s]', '', text)                                # menghapus karakter selain huruf dan angka
    text = text.replace('\n', ' ')                                     # mengganti baris baru dengan spasi
    text = text.translate(str.maketrans('', '', string.punctuation))   # menghapus semua tanda baca
    text = text.strip(' ')                                             # menghapus karakter spasi dari kiri dan kanan teks
    return text

def casefoldingText(text):
    text = text.lower()
    return text

def tokenizingText(text):
    text = word_tokenize(text)
    return text

def filteringText(text):
    listStopwords = set(nltk.corpus.stopwords.words('indonesian'))
    listStopwords1 = set(nltk.corpus.stopwords.words('english'))
    listStopwords.update(listStopwords1)
    listStopwords.update(['iya','yaa','gak','nya','na','sih','ku',
                          'di','ga','ya','gaa','loh','kah','woi',
                          'woii','woy'])
    filtered = []
    for txt in text:
        if txt not in listStopwords:
            filtered.append(txt)
    text = filtered
    return text

def stemmingText(text):
    words = text.split()
    stemmed_words = [stemmer.stem(word) for word in words]  # menggunakan stemmer dari cell Inisialisasi Sastrawi
    stemmed_text = ' '.join(stemmed_words)
    return stemmed_text

def toSentence(list_words):
    sentence = ' '.join(word for word in list_words)
    return sentence

# mendefinisikan kembali fungsi slangword yang sebenarnya
slangwords = {"@": "di", "abis": "habis", "wtb": "beli", "masi": "masih", "wts": "jual", "wtt": "tukar", "bgt": "banget", "maks": "maksimal", "leq": "lag", "didonlot": "didonwload",
              "lelet": "lambat", "tp": "tapi", "yg": "yang", "ngeleg": "ngelag", "spyletter": "SPayLater", "blm": "belum", "apk": "aplikasi","skarang": "sekarang", "qrish": "QRIS",
              "g": "gak", "ny": "nya", "pnya": "punya", "uda": "sudah", "tdk": "tidak", "elu": "kamu", "layan": "layanan", "sya": "saya", "mmbaik": "membaik"}
def fix_slangwords(text):
    words = text.split()
    fixed_words = []

    for word in words:
        if word.lower() in slangwords:
            fixed_words.append(slangwords[word.lower()])
        else:
            fixed_words.append(word)

    fixed_text = ' '.join(fixed_words)
    return fixed_text

# menerapkan semua fungsi preprocessing ke dataframe
# membutuhkan waktu sekitar ~20menit karena menggunakan 12000 data

# cleaning - menghapus karakter tidak penting
clean_df['content'] = clean_df['content'].apply(cleaningText)

# casefolding - mengubah semua huruf jadi kecil
clean_df['content'] = clean_df['content'].apply(casefoldingText)

# fix slangword - mengubah kata tidak baku jadi baku
clean_df['content'] = clean_df['content'].apply(fix_slangwords)

# tokenizing - pecah kalimat menjadi list kata
clean_df['text_token'] = clean_df['content'].apply(tokenizingText)

# filtering - menghapus stopword
clean_df['text_stopword'] = clean_df['text_token'].apply(filteringText)

# stemming - mengubah kata ke bentuk dasar
clean_df['text_stemmed'] = clean_df['text_stopword'].apply(lambda x: stemmingText(' '.join(x)))

# menggunakan hasil stemming
clean_df['clean_text'] = clean_df['text_stemmed']

# hapus baris yang clean_text nya kosong setelah preprocessing
clean_df = clean_df[clean_df['clean_text'].str.strip() != ''].reset_index(drop=True)

print("Preprocessing selesai!")
print(f"Total data: {len(clean_df)}")
clean_df[['content', 'clean_text']].head()

"""**Load lexicon sentimen bahasa Indonesia**"""

# berisi daftar kata positif dan negatif beserta nilainya
# referensi kamus lexicon yang digunakan

url_pos = "https://raw.githubusercontent.com/fajri91/InSet/master/positive.tsv"
url_neg = "https://raw.githubusercontent.com/fajri91/InSet/master/negative.tsv"

# ngeload kamus positif dan negatif
# header=0 = baris pertama dijadikan header otomatis

pos_df = pd.read_csv(url_pos, sep='\t', header=0)
neg_df = pd.read_csv(url_neg, sep='\t', header=0)

print(pos_df.head())
print(pos_df.columns.tolist())

# mengubah bentuk dictionary
positive_lexicon = dict(zip(pos_df['word'], pos_df['weight'].astype(float)))
negative_lexicon = dict(zip(neg_df['word'], neg_df['weight'].astype(float)))
print(f"Jumlah kata positif: {len(positive_lexicon)}")
print(f"Jumlah kata negatif: {len(negative_lexicon)}")

# menambahkan dan mengoreksi kata yang bernilai salah di Inset

positive_lexicon['bagus']   = 3.0
positive_lexicon['baik']    = 2.0
positive_lexicon['baguss']  = 3.0
positive_lexicon['keren']   = 3.0
positive_lexicon['mantap']  = 3.0
positive_lexicon['mudah']   = 2.0
positive_lexicon['senang']  = 2.0
positive_lexicon['suka']    = 2.0
positive_lexicon['hebat']   = 3.0
positive_lexicon['canggih'] = 2.0
positive_lexicon['aplikasi'] = 3.0
positive_lexicon['membaik'] = 3.0

negative_lexicon['stuck']   = -2.0
negative_lexicon['error']   = -3.0
negative_lexicon['lemot']   = -2.0
negative_lexicon['lambat']  = -2.0
negative_lexicon['rusak']   = -3.0
negative_lexicon['kecewa']  = -3.0
negative_lexicon['buruk']   = -3.0
negative_lexicon['jelek']   = -3.0
negative_lexicon['susah']   = -2.0
negative_lexicon['masalah'] = -2.0

# menghapus kata 'aplikasi' dari referensi kamus negatif jika ada untuk keperluan nilai polarity dari (clean_text) dari distribusi label
if 'aplikasi' in negative_lexicon:
    del negative_lexicon['aplikasi']

print("koreksi lexicon selesai")

"""**Pelabelan data**"""

# input = clean_text yang sudah di preprocessing
# output = polarity_score (angka) + polarity (label)
def sentiment_analysis_lexicon_indonesia(text):
    tokens = text.split()

    # menghitung total skor dari setiap kata
    score = 0
    for word in tokens:
        if word in positive_lexicon:
            score += positive_lexicon[word]
        if word in negative_lexicon:
            score += negative_lexicon[word]

    # menentukan label berdasarkan total skor
    if score > 0:
        polarity = 'positif'
    elif score < 0:
        polarity = 'negatif'
    else:
        polarity = 'netral'

    return score, polarity

results = clean_df['clean_text'].apply(sentiment_analysis_lexicon_indonesia)
results = list(zip(*results))
clean_df['polarity_score'] = results[0]
clean_df['polarity']       = results[1]
print("\ndistribusi label:")
print(clean_df['polarity'].value_counts())
clean_df[['content', 'clean_text', 'polarity_score', 'polarity']].head(20)

# ada yang tidak wajar dari clean_text ke hasil polarity nya (ambigu)
# mungkin karena keterbatasan dari referensi kamus lexicon yang saya gunakan

"""**Visualisasi distribusi label sentimen & polarity**"""

import matplotlib.pyplot as plt

colors = ['#3498DB', '#e74c3c', '#000000']
clean_df['polarity'].value_counts().plot(
    kind='bar',
    color=colors,
    title='Distribusi Label Sentimen (Lexicon-Based)',
    figsize=(7, 5)
)
plt.xlabel('Sentimen')
plt.ylabel('Jumlah Data')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# histogram polarity score
axes[0].hist(clean_df['polarity_score'], bins=30, color='steelblue', edgecolor='black')
axes[0].set_title('Distribusi Polarity Score')
axes[0].set_xlabel('Polarity Score')
axes[0].set_ylabel('Jumlah data')

# pie chart distribusi label
label_counts = clean_df['polarity'].value_counts()
axes[1].pie(
    label_counts,
    labels=label_counts.index,
    autopct='%1.1f%%',
    colors=['#3498DB', '#e74c3c', '#000000'],
    startangle=90)
axes[1].set_title('Proporsi Label Sentimen')

plt.tight_layout()
plt.show()

# kata yang paling banyak keluar atau muncul
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(clean_df['clean_text'])
tfidf_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df = tfidf_df.sum().reset_index(name='jumlah')
tfidf_df = tfidf_df.sort_values('jumlah', ascending=False).head(30)
sns.barplot(x='jumlah', y='index', data=tfidf_df)
plt.title('Kata-kata yang paling sering digunakan')
plt.show()

"""**Word cloud**"""

# world cloud umum
from wordcloud import WordCloud

text_all = ' '.join(clean_df['clean_text'].values)
wc_all = WordCloud(width=1000, height=500, background_color='white').generate(text_all)

plt.figure(figsize=(10, 5))
plt.imshow(wc_all, interpolation='bilinear')
plt.title('Word cloud umum')
plt.axis('off')
plt.show()

# word cloud positif
text_pos = ' '.join(clean_df[clean_df['polarity'] == 'positif']['clean_text'].values)
wc_pos = WordCloud(width=1000, height=500, background_color='white', colormap='Greens').generate(text_pos)

plt.figure(figsize=(10, 5))
plt.imshow(wc_pos, interpolation='bilinear')
plt.title('Word cloud positif')
plt.axis('off')
plt.show()

# word cloud negatif
text_neg = ' '.join(clean_df[clean_df['polarity'] == 'negatif']['clean_text'].values)
wc_neg = WordCloud(width=1000, height=500, background_color='white', colormap='Reds').generate(text_neg)

plt.figure(figsize=(10, 5))
plt.imshow(wc_neg, interpolation='bilinear')
plt.title('Word Cloud Negatif')
plt.axis('off')
plt.show()

# word cloud netral
text_net = ' '.join(clean_df[clean_df['polarity'] == 'netral']['clean_text'].values)
wc_net = WordCloud(width=800, height=400, background_color='white', colormap='Greys').generate(text_net)

plt.figure(figsize=(10, 5))
plt.imshow(wc_net, interpolation='bilinear')
plt.title('Word Cloud Netral')
plt.axis('off')
plt.show()

"""**Balancing data**"""

# Tujuan : menyeimbangkan jumlah data tiap kelas, agar model tidak bias ke kelas yang dominan
# kalau tidak dibalance, model akan lebih mudah mengenali positif tapi sulit mengenali netral karena datanya sedikit

df_pos = clean_df[clean_df['polarity'] == 'positif']
df_neg = clean_df[clean_df['polarity'] == 'negatif']
df_net = clean_df[clean_df['polarity'] == 'netral']

print(f"Sebelum balancing:")
print(f"Positif : {len(df_pos)}")
print(f"Negatif : {len(df_neg)}")
print(f"Netral  : {len(df_net)}")

# samakan ke kelas terkecil (minimal 1000)
min_size = max(1000, min(len(df_pos), len(df_neg), len(df_net)))

df_pos_bal = resample(df_pos, n_samples=min_size, random_state=42)
df_neg_bal = resample(df_neg, n_samples=min_size, random_state=42)
df_net_bal = resample(df_net, n_samples=min_size, random_state=42)

# menggabungkan dan mengacak urutan data
clean_df = pd.concat([df_pos_bal, df_neg_bal, df_net_bal])
clean_df = clean_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"\nSetelah balancing:")
print(clean_df['polarity'].value_counts())
print(f"Total data: {len(clean_df)}")

"""**Data Splitting**"""

X = clean_df['clean_text'].values # fitur
y = clean_df['polarity'].values # label (positif/negatif/netral)

# split data 80/20 untuk skema pelatihan 1 dan 2
X_train_80, X_test_80, y_train_80, y_test_80 = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# split data 70/30 untuk skema pelatihan 3
X_train_70, X_test_70, y_train_70, y_test_70 = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y)

print(f"split 80/20 = train: {len(X_train_80)}, test: {len(X_test_80)}")
print(f"split 70/30 = train: {len(X_train_70)}, test: {len(X_test_70)}")

"""**Skema 1: SVM + TF-IDF**"""

# SVM    : mencari batas pemisah optimal antar kelas
# TF-IDF : mengubah teks menjadi vektor angka berdasarkan seberapa penting suatu kata dalam dokumen

# ekstraksi fitur TF-IDF
# max_features : mengambil 20.000 kata paling penting
# ngram_range  : (1,2) = unigram dan bigram
tfidf_skema1   = TfidfVectorizer(max_features=20000, ngram_range=(1, 2))
X_train_tfidf1 = tfidf_skema1.fit_transform(X_train_80)
X_test_tfidf1  = tfidf_skema1.transform(X_test_80)

# pelatihan model SVM
# kernel='linear'
model_svm = SVC(kernel='linear', C=1.0, random_state=42)
model_svm.fit(X_train_tfidf1, y_train_80)

# evaluasi
y_pred_svm    = model_svm.predict(X_test_tfidf1)
acc_train_svm = model_svm.score(X_train_tfidf1, y_train_80)
acc_test_svm  = accuracy_score(y_test_80, y_pred_svm)

print("SKEMA 1: SVM + TF-IDF dengan data splitting 80/20")
print()
print(f"Train Accuracy : {acc_train_svm:.4f} ({acc_train_svm*100:.2f}%)")
print(f"Test Accuracy  : {acc_test_svm:.4f} ({acc_test_svm*100:.2f}%)")
print("\nClassification Report:")
print(classification_report(y_test_80, y_pred_svm))

"""**Skema 2: RandomForest + TF-IDF**"""

# RandomForest       : menggabungkan banyak decision tree
# TF-IDF : mengubah teks menjadi vektor angka berdasarkan seberapa penting suatu kata dalam dokumen

# ekstraksi fitur TF-IDF
tfidf_skema2   = TfidfVectorizer(max_features=15000, ngram_range=(1, 3))
X_train_tfidf2 = tfidf_skema2.fit_transform(X_train_80)
X_test_tfidf2  = tfidf_skema2.transform(X_test_80)

# pelatihan model RandomForest
model_rf_w2v = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
model_rf_w2v.fit(X_train_tfidf2, y_train_80)

# evaluasi
y_pred_rf_w2v    = model_rf_w2v.predict(X_test_tfidf2)
acc_train_rf_w2v = model_rf_w2v.score(X_train_tfidf2, y_train_80)
acc_test_rf_w2v  = accuracy_score(y_test_80, y_pred_rf_w2v)

print("SKEMA 2: RandomForest + TF-IDF dengan data splitting 80/20")
print()
print(f"Train Accuracy : {acc_train_rf_w2v:.4f} ({acc_train_rf_w2v*100:.2f}%)")
print(f"Test Accuracy  : {acc_test_rf_w2v:.4f} ({acc_test_rf_w2v*100:.2f}%)")
print("\nClassification Report:")
print(classification_report(y_test_80, y_pred_rf_w2v))

"""**Skema 3: Logistic Regression + TF-IDF**"""

# Logistic regression : algoritma klasifikasi yg menghitung probabilitas dimana suatu data masuk ke suatu kelas tertentu

from sklearn.linear_model import LogisticRegression

# ekstraksi fitur TF-IDF
tfidf_skema3   = TfidfVectorizer(max_features=20000, ngram_range=(1, 2))
X_train_tfidf3 = tfidf_skema3.fit_transform(X_train_70)
X_test_tfidf3  = tfidf_skema3.transform(X_test_70)

# pelatihan model Logistic Regression
model_lr = LogisticRegression(max_iter=1000, random_state=42)
model_lr.fit(X_train_tfidf3, y_train_70)

# evaluasi
y_pred_lr    = model_lr.predict(X_test_tfidf3)
acc_train_lr = model_lr.score(X_train_tfidf3, y_train_70)
acc_test_lr  = accuracy_score(y_test_70, y_pred_lr)

print("SKEMA 3: Logistic Regression + TF-IDF dengan data splitting 70/30")
print()
print(f"Train Accuracy : {acc_train_lr:.4f} ({acc_train_lr*100:.2f}%)")
print(f"Test Accuracy  : {acc_test_lr:.4f} ({acc_test_lr*100:.2f}%)")
print("\nClassification Report:")
print(classification_report(y_test_70, y_pred_lr))

"""**Evaluasi Model: Dengan 3 Skema(algoritma) dan 2 Kombinasi(ekstraksi fitur/pembagian data)**</br>
* *Kombinasi 1: Algoritma yang digunakan berbeda (SVM, RandomForest, Logistic Regression)*
* *Kombinasi 2: Data splitting yang digunakan berbeda (80/20, 70/30)*
"""

# tabel perbandingan dataframe
results_df = pd.DataFrame({
    'Model': ['SVM', 'RandomForest', 'Logistic Regression'],
    'Accuracy Train': [acc_train_svm, acc_train_rf_w2v, acc_train_lr],
    'Accuracy Test': [acc_test_svm, acc_test_rf_w2v, acc_test_lr]})
results_df

# perbandingan evaluasi + clasification report
print("\nAkurasi SVM - Training: {:.2f}%".format(acc_train_svm * 100))
print("Akurasi SVM - Testing : {:.2f}%".format(acc_test_svm * 100))

print("\nAkurasi RandomForest - Training: {:.2f}%".format(acc_train_rf_w2v * 100))
print("Akurasi RandomForest - Testing : {:.2f}%".format(acc_test_rf_w2v * 100))

print("\nAkurasi Logistic Regression - Training: {:.2f}%".format(acc_train_lr * 100))
print("Akurasi Logistic Regression - Testing : {:.2f}%".format(acc_test_lr * 100))

print("\nClassification Report - SVM:")
print(classification_report(y_test_80, y_pred_svm))

print("\nClassification Report - Random Forest:")
print(classification_report(y_test_80, y_pred_rf_w2v))

print("\nClassification Report - Logistic Regression:")
print(classification_report(y_test_70, y_pred_lr))

# tabel perbandingan
print(f"{'Skema':<10} {'Algoritma':<22} {'Fitur':<12} {'Split':<8} {'Train Acc':>10} {'Test Acc':>10}")
print()
print(f"{'Skema 1':<10} {'SVM':<22} {'TF-IDF':<12} {'80/20':<8} {acc_train_svm:>10.4f} {acc_test_svm:>10.4f}")
print(f"{'Skema 2':<10} {'Random Forest':<22} {'TF-IDF':<12} {'80/20':<8} {acc_train_rf_w2v:>10.4f} {acc_test_rf_w2v:>10.4f}")
print(f"{'Skema 3':<10} {'Logistic Regression':<22} {'TF-IDF':<12} {'70/30':<8} {acc_train_lr:>10.4f} {acc_test_lr:>10.4f}")
print()

skema_label = [
    'Skema 1\nSVM+TFIDF\n80/20',
    'Skema 2\nRF+TFIDF\n80/20',
    'Skema 3\nLR+TFIDF\n70/30']

"""**Inference**"""

# fungsi preprocessing untuk interface
def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = stopword.remove(text)
    text = stemmer.stem(text)
    return text

# karena model svm memiliki akurasi test yang tinggi, maka akan menggunakan model tersebut
def predict_sentiment(text):
    # preprocessing teks input
    clean = preprocess(text)

    # ekstraksi fitur menggunakan vectorizer skema 1
    vector = tfidf_skema1.transform([clean])

    # prediksi sentimen
    prediction = model_svm.predict(vector)

    return prediction[0]

# testing inference dengan beberapa contoh kalimat
test_kalimat = [
    "bagus banget aplikasinya, puas belanja disini",
    "jelek banget, buruk, tidak suka",
    "biasa saja"]

print("hasil inference")
for kalimat in test_kalimat:
    hasil = predict_sentiment(kalimat)
    print(f"\nInput  : {kalimat}")
    print(f"Output : {hasil.upper()}")

"""**Simpan Model**"""

import pickle

# simpan model SVM (terbaik)
with open('model_sentimen.pkl', 'wb') as f:
    pickle.dump(model_svm, f)

# simpan vectorizer TF-IDF skema 1
with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf_skema1, f)

# simpan dataset final yang sudah ada label
clean_df.to_csv('ulasan_shopee_labeled.csv', index=False)

print("Model, vectorizer, dan dataset berhasil disimpan!")

"""**Requirements.txt**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# google-play-scraper==1.2.7
# pandas
# numpy
# matplotlib
# scikit-learn
# PySastrawi
# nltk
# gensim
# wordcloud
# seaborn
# string
# re
# pickle
# collections